/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/aq0QUAOqWDQ
 */
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Card, CardContent } from "@/components/ui/card"
import Image from "next/image";

export default function ProfilePage() {
  const cardData = [
    {
      title: "Next.js",
      description: "The React Framework – created and maintained by @vercel.",
      src: "/placeholder.svg"
    },
    {
      title: "React",
      description: "A JavaScript library for building user interfaces.",
      src: "/placeholder.svg"
    },
    {
      title: "Vue.js",
      description: "The Progressive JavaScript Framework.",
      src: "/placeholder.svg"
    },
    {
      title: "Angular",
      description: "A platform and framework for building single-page client applications using HTML and TypeScript.",
      src: "/placeholder.svg"
    },
    {
      title: "Svelte",
      description: "A radical new approach to building user interfaces.",
      src: "/placeholder.svg"
    }
  ];
  return (
    <div className="grid max-w-3xl gap-4 px-4 mx-auto lg:grid-cols-2 lg:gap-6 xl:gap-8">
      <div className="space-y-4 lg:col-span-2">
        <div className="space-y-2">
          <div className="flex items-center space-x-4">
            <Avatar className="w-16 h-16">
              <AvatarImage alt="@shadcn" src="/placeholder-avatar.jpg" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
            <div className="space-y-1.5">
              <h1 className="text-3xl font-bold">@shadcn</h1>
              <div className="flex items-center space-x-2 text-sm">
                <p>0xUehddhuiehiuehdw89137</p>
              </div>
            </div>
          </div>
        </div>
        <div className="grid gap-4 text-sm lg:grid-cols-2">
          <div className="space-y-4">
            <div className="space-y-2">
              <h2 className="text-lg font-semibold">Your Projects</h2>
              {/* <p className="text-sm text-gray-500 dark:text-gray-400">You haven’t created any projects yet.</p> */}
              <div className="grid gap-4 p-4 text-sm">
                {cardData.map((data, index) => (
                  <Card key={index} className="w-full overflow-hidden">

                    <CardContent className="flex p-0 gap-4">

                      {/* <Image width={200} height={100} className="md:object-contain" src={data.src} alt={data.title} /> */}
                      <div className="min-h-24 m-1">

                        <div className="absolute m-1 aspect-square bg-gray-100 rounded-lg overflow-hidden dark:bg-gray-800">
                          <Image alt="Avatar" className="aspect-[1/1] object-cover" height="80" src={data.src} width="80" />
                        </div>
                      </div>
                      <div className="p-2 ml-20">
                        <div className="text-left">
                          <h2 className="text-xl font-semibold ">{data.title}</h2>
                          <p className="text-sm text-gray-600">{data.description}</p>
                          {/* <p className="text-sm ">{data.contributors}</p> */}
                        </div>
                      </div>

                    </CardContent>
                  </Card>
                ))}
              </div>
            </div>
            <div className="space-y-2">
              <h2 className="text-lg font-semibold">Your Events</h2>
              <p className="text-sm text-gray-500 dark:text-gray-400">You haven’t created any events yet.</p>

            </div>
          </div>
          <div className="space-y-4">
            <div className="space-y-2">
              <h2 className="text-lg font-semibold">Your Contributions</h2>
              <p className="text-sm text-gray-500 dark:text-gray-400">You haven’t contributed to any projects yet.</p>
            </div>
          </div>
        </div>
      </div>

    </div>
  )
}

